import subprocess
import os
from pathlib import Path

import importlib.metadata
import json
import requests
import sys

REPO_URL = "git+https://github.com/ClementPla/DNAi.git"


def pip_install_command():
    """Upgrade DNAi in the environment of the running interpreter, without
    reinstalling dependencies that are already satisfied (e.g. a CUDA torch)."""
    return [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--upgrade",
        "--upgrade-strategy",
        "only-if-needed",
        REPO_URL,
    ]


def windows_update_worker(parent_pid):
    """Source of a standalone script (no dnafiber import, so nothing of the
    package stays locked) that waits for `parent_pid` to exit, then updates."""
    return f"""
import ctypes, subprocess, time
SYNCHRONIZE, INFINITE = 0x00100000, 0xFFFFFFFF
kernel32 = ctypes.windll.kernel32
print("Waiting for DNAi to close...")
handle = kernel32.OpenProcess(SYNCHRONIZE, False, {parent_pid})
if handle:
    kernel32.WaitForSingleObject(handle, INFINITE)
    kernel32.CloseHandle(handle)
time.sleep(2)  # let the DNAI.exe launcher exit too
print("Updating DNAi from GitHub...")
if subprocess.call({pip_install_command()!r}) == 0:
    print("\\nUpdate complete. You can now restart DNAi.")
else:
    print("\\nUpdate FAILED. See the messages above.")
input("Press Enter to close this window...")
"""


def get_local_commit(package_name="dnafiber"):
    """Return commit hash from dnafiber/_version.py or fallback strategies."""
    try:
        # Preferred: check dnafiber/_version.py (generated by poetry-dynamic-versioning)
        try:
            from dnafiber._version_ import version

            if "+" in version:
                # format like "0.2.0+g123abc"
                return version.split("+")[-1].lstrip("g")
        except ImportError:
            # fallback: ask git directly
            import subprocess

            return (
                subprocess.check_output(["git", "rev-parse", "HEAD"]).decode().strip()
            )

        # Fallback 1: check direct_url.json
        metadata = importlib.metadata.distribution(package_name)
        direct_url = metadata.read_text("direct_url.json")
        if direct_url:
            url_info = json.loads(direct_url)
            commit = url_info.get("vcs_info", {}).get("commit_id")
            if commit:
                return commit

        # Fallback 2: check .git if present
        pkg_path = Path(metadata.locate_file(""))
        git_dir = pkg_path.parent / ".git"
        if git_dir.exists():
            commit = (
                subprocess.check_output(
                    ["git", "rev-parse", "HEAD"], cwd=pkg_path.parent
                )
                .decode()
                .strip()
            )
            return commit
    except Exception as e:
        print(f"Could not determine local commit: {e}")

    return None


def get_remote_commit(repo="ClementPla/DNAi"):
    """Return latest commit hash from GitHub main branch."""
    url = f"https://api.github.com/repos/{repo}/commits/main"
    r = requests.get(url, timeout=5)
    r.raise_for_status()
    return r.json()["sha"]


def check_version():
    local = get_local_commit()
    if not local:
        print("⚠️ Could not determine local commit. Proceeding without update check.")
        return
    local = local[:7]
    remote = get_remote_commit()[:7]
    if local != remote:
        print(
            f"⚠️ Your install is outdated.\nLocal: {local[:7]} vs Remote: {remote[:7]}"
        )
        print(
            f"👉 Run: {subprocess.list2cmdline(pip_install_command())} or auto-update"
        )
    else:
        print("✅ You are on the latest version.")

    return local == remote


def main():
    try:
        valid = check_version()
    except Exception as e:
        print(f"Could not check for updates: {e}")
        valid = None

    if valid is None:
        pass  # Couldn't check, continue to app
    elif not valid:
        try:
            response = input("Do you want to update now? [y/N]: ")
        except EOFError:
            response = ""
        if response.strip().lower() == "y":
            if sys.platform == "win32":
                # The running DNAI.exe/python.exe are locked on Windows, so the
                # update runs in its own console once this process has exited.
                subprocess.Popen(
                    [sys.executable, "-c", windows_update_worker(os.getpid())],
                    creationflags=subprocess.CREATE_NEW_CONSOLE,
                )
                print(
                    "Update starting in a new window. Close any other DNAi window, "
                    "then restart DNAi once it is complete."
                )
            else:
                # Installed files can be replaced while running on Linux/macOS,
                # so update in the foreground and report the result.
                print("Updating DNAi from GitHub...")
                result = subprocess.run(pip_install_command())
                if result.returncode != 0:
                    print("❌ Update failed. See the messages above.")
                    sys.exit(result.returncode)
                print("✅ Update complete. Please restart DNAi.")
            sys.exit(0)

    # Start the Streamlit application
    print("Starting Streamlit application...")
    local_dir = os.path.dirname(os.path.abspath(__file__))
    subprocess.run(
        [
            sys.executable,
            "-m",
            "streamlit",
            "run",
            os.path.join(local_dir, "ui", "Welcome.py"),
        ],
    )


if __name__ == "__main__":
    if main():
        print("Streamlit application started successfully.")
